apiVersion: apps/v1
kind: Deployment
metadata:
  name: s3-api
  namespace: s3-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: s3-api
  template:
    metadata:
      labels:
        app: s3-api
    spec:
      volumes:
        - name: s3-api-jwt-secret
          secret:
            secretName: s3-api-jwt-secret
        - name: storage-cluster-config
          secret:
            secretName: storage-cluster-config   
      containers:
        - name: s3-api
          image: gitlab.local:5050/anthonybudd/api:master
          imagePullPolicy: Always
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "-c", "sequelize db:migrate"]
          ports:
          - containerPort: 80
          volumeMounts:
          - name: s3-api-jwt-secret
            mountPath: "/app/private.pem"
            subPath: private.pem
          - name: s3-api-jwt-secret
            mountPath: "/app/public.pem"
            subPath: public.pem
          - name: storage-k8s-config
            mountPath: "/app/config"
            subPath: storage-config
          env:
          - name: S3_ROOT
            value: "s3.anthonybudd.io"
          - name: K8S_CONFIG_PATH
            value: "/app/k8s-config"
          - name: NODE_ENV
            value: "production"
          - name: FRONTEND_URL
            value: "https://s3.anthonybudd.io"
          - name: BACKEND_URL
            value: "https://s3-api.anthonybudd.io/api/v1"
          - name: PORT
            value: "80"
          - name: PRIVATE_KEY_PATH
            value: "/app/private.pem"
          - name: PUBLIC_KEY_PATH
            value: "/app/public.pem"
          - name: DB_HOST
            value: "s3-db"
          - name: DB_PORT
            value: "3306"
          - name: DB_USERNAME
            value: "app"
          - name: DB_DATABASE
            value: "app"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: s3-api-secrets
                key: DB_PASSWORD
          - name: HCAPTCHA_SECRET
            valueFrom:
              secretKeyRef:
                name: s3-api-secrets
                key: HCAPTCHA_SECRET
