# Install VS Code extension rest-client 
# URL: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# @host=http://localhost:8888/api/v1
@host=http://api.local/api/v1
@AccessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJpZCI6ImM0NjQ0NzMzLWRlZWEtNDdkOC1iMzVhLTg2ZjMwZmY5NjE4ZSIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsImZpcnN0TmFtZSI6IlVzZXIiLCJsYXN0TmFtZSI6Ik9uZSIsImlhdCI6MTcxMjgxNDM2NCwiZXhwIjozNDI1NzE1MTI4fQ.oU5Qu_Hg3xiXSmbfvbyHRyFyGmmoqzWSvEoID5npzMr2Hx0HNlNXFV1BKLy4nhgGV9H9xY2_XFz8dfSLMD-IHSl9tRDR5XauZzpk4cBHr1h5jEEz7Ld94vb9snKshgAcjSsfvn4lEsbXNgrf-2CVyc5nt6oaftkzK6G_B3-gS4M3g5HCwmQUSoApmgWaYaQQZNKdHJnPxzBpXZow_UkuL2OnrocTvHYb3uK51a620uR7oQa9CMWq62YbZ38RENJ6Ri6cWMtrgra_4bfhiltJ0xb9FFMDF7_sL_YBNgvta3CuEJq98uAebNTxQZq60M8zu5Hcs9dwJEM1_t1Gtx6tyg

###########################################
# Auth

POST {{host}}/auth/login
content-type: application/json

{
    "email": "user@example.com",
    "password": "Password@1234"
}

### Check auth
GET {{host}}/_authcheck
Authorization: Bearer {{AccessToken}}


###########################################
# Buckets

GET {{host}}/buckets
Authorization: Bearer {{AccessToken}}


### Get Bucket by ID
GET {{host}}/buckets/fae8a1fb-bc90-4565-b567-1fe6846544de
Authorization: Bearer {{AccessToken}}


### Create Bucket
POST {{host}}/buckets
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "name": "x-test"
}