# Install VS Code extension rest-client 
# URL: https://marketplace.visualstudio.com/items?itemName=humao.rest-client

@host=http://localhost:8888/api/v1
# @host=http://api.local/api/v1
@AccessToken=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzUxMiJ9.eyJpZCI6ImM0NjQ0NzMzLWRlZWEtNDdkOC1iMzVhLTg2ZjMwZmY5NjE4ZSIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsImZpcnN0TmFtZSI6IlVzZXIiLCJsYXN0TmFtZSI6Ik9uZSIsImlhdCI6MTcxMjg5NDI5NywiZXhwIjozNDI1ODc0OTk0fQ.O4XnEFAlh-08RSfBECB4s2xxf-dWBDqo4KFJGH_2kWm-A1gM_eELgA1eM_yxxpStjIFLJ_NAUPf8W1zN1gyKk2-zCBIG17Q4eW-8iKMLAGQUsRsRq8B1KPt8oQXl5Wx-VqFfoLAZNl_OLniaOwGj8BmqEnU74_FVw8PCBN5AhGcme1An5MmsIBp3kWezZ5g4ZHVIKfKmWEWUxjhVVclkHn3OrLMIeQUKxBdEDEgSRTJRXYJAycnzxZX9QtOgQO1G_aBzNbocUKOgyEE5OKTNJ7hONijENLCNv8LbKr0Wg3a0e1gYY4Y8FszQsvbjTTYVJbz2dey5qYfLcvSjCO2S4w

###########################################
# Auth

POST {{host}}/auth/login
content-type: application/json

{
    "email": "user@example.com",
    "password": "Password@1234"
}

### Check auth
GET {{host}}/_authcheck
Authorization: Bearer {{AccessToken}}


###########################################
# Buckets

GET {{host}}/buckets
Authorization: Bearer {{AccessToken}}


### Create Bucket
POST {{host}}/buckets
Authorization: Bearer {{AccessToken}}
content-type: application/json

{
    "name": "x-test"
}

### Delete Bucket
DELETE {{host}}/buckets/fae8a1fb-bc90-4565-b567-1fe6846544de
Authorization: Bearer {{AccessToken}}
